version: '3'

services:
  mpm_input_preprocessing:
    image: mpm_input_preprocessing:dev
    entrypoint:
      - uvicorn
      - mpm_input_preprocessing.http.api:api
      - --host
      - "0.0.0.0"
      - --port
      - "8082"
      - --log-config
      - /home/apps/mpm_input_preprocessing/logging.yaml
      - --workers
      - "1"
      - "--reload"
    ports:
      - 8082:8082
    volumes:
      - ./mpm_input_preprocessing:/home/apps/mpm_input_preprocessing
      - ./aws/credentials:/home/apps/.aws/credentials
      - ./logging.yaml:/home/apps/mpm_input_preprocessing/logging.yaml

    env_file:
      - ./.env
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"


